"""
alembic/env.py

This is the Alembic environment configuration.
It tells Alembic:
  1. How to connect to the database
  2. Where your SQLAlchemy models are (so it can detect schema changes)

🧠 KEY CONCEPT — Two migration modes:
  - offline: generates SQL scripts to run manually (useful for DBAs)
  - online:  connects to DB directly and runs migrations immediately

We configure BOTH here. Production typically uses online mode.

🧠 KEY CONCEPT — target_metadata:
  This is the MOST important setting.
  By setting target_metadata = Base.metadata, we tell Alembic:
  "Compare the current database schema against these SQLAlchemy models,
   and generate the SQL needed to make them match."
  
  This is what makes "autogenerate" work:
    alembic revision --autogenerate -m "add users table"
  Alembic reads Base.metadata → compares to actual DB → writes the migration.
"""

import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from alembic import context

# ── Add project root to Python path ──────────────────────────────────────────
# Without this, `from app.db.session import Base` would fail
# because alembic/ is not in the Python path by default.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# ── Import your app's Base and ALL models ─────────────────────────────────────
# CRITICAL: You must import every model file here.
# If a model is not imported, Alembic won't know about that table
# and won't include it in autogenerated migrations.
from app.db.session import Base        # noqa
from app.models.user import User       # noqa: F401 — must import to register
from app.models.interview import (     # noqa: F401 — must import to register
    InterviewSession,
    InterviewQuestion,
    QuestionFeedback,
)
from app.core.config import settings

# ── Alembic Config ────────────────────────────────────────────────────────────
config = context.config

# Override the sqlalchemy.url from alembic.ini with our app's settings
# This ensures we always use the same DATABASE_URL as the app
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Setup Python logging from alembic.ini config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# This is the object Alembic inspects to autogenerate migrations
target_metadata = Base.metadata


# ── Offline Mode ──────────────────────────────────────────────────────────────
def run_migrations_offline() -> None:
    """
    Run migrations without connecting to the database.
    Generates raw SQL statements that a DBA can review and run manually.
    
    Useful in environments where the migration tool can't connect to DB directly.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


# ── Online Mode ───────────────────────────────────────────────────────────────
def run_migrations_online() -> None:
    """
    Run migrations with a live database connection.
    This is the standard mode for development and production.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # No pooling during migrations
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,  # Detect column type changes (e.g., String→Text)
        )
        with context.begin_transaction():
            context.run_migrations()


# ── Run ───────────────────────────────────────────────────────────────────────
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
